export const TBUTTON_VARIANT = {
  PRIMARY: "PRIMARY",
  VIEW_MORE: "VIEW_MORE",
  BASE_ORANGE: "BASE_ORANGE",
  DELETE: "DELETE",
  SUCCESS: "SUCCESS",
  EXCEL: "EXCEL",
}

export const TBUTTON_SIZE = {
  SMALL: "SMALL",
  MEDIUM: "MEDIUM",
  LARGE: "LARGE",
}